# Generated by Django 4.2.2 on 2024-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='attemtps',
        ),
        migrations.AddField(
            model_name='mailing',
            name='attemtps',
            field=models.ManyToManyField(related_name='mailings_attempts', to='letters.mailingattempt', verbose_name='Попытки'),
        ),
    ]
